import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types types/`.

export enum NotesStatus {
    DRAFT = "draft",
    PUBLISHED = "published",
    ARCHIVED = "archived"
}

export enum ReactionsTargetType {
    NOTE = "note",
    COMMENT = "comment"
}

export enum CollaboratorsPermission {
    READ = "read",
    WRITE = "write",
    ADMIN = "admin"
}

export enum NoteRevisionsCause {
    MANUAL = "manual",
    AI = "ai",
    COLLAB = "collab"
}

export enum SubscriptionsPlan {
    FREE = "free",
    PRO = "pro",
    ORG = "org"
}

export enum SubscriptionsStatus {
    ACTIVE = "active",
    CANCELED = "canceled",
    TRIALING = "trialing"
}

export enum MessagesType {
    TEXT = "text",
    IMAGE = "image",
    VIDEO = "video",
    AUDIO = "audio",
    FILE = "file",
    CALL_SIGNAL = "call_signal",
    SYSTEM = "system"
}

export enum ConversationsType {
    DIRECT = "direct",
    GROUP = "group",
    CHANNEL = "channel",
    BROADCAST = "broadcast",
    COMMUNITY = "community"
}

export enum ContactsRelationship {
    FRIEND = "friend",
    FAMILY = "family",
    COLLEAGUE = "colleague",
    ACQUAINTANCE = "acquaintance",
    BLOCKED = "blocked",
    FAVORITE = "favorite"
}

export enum FollowsStatus {
    PENDING = "pending",
    ACCEPTED = "accepted",
    BLOCKED = "blocked"
}

export enum AppActivityStatus {
    ONLINE = "online",
    OFFLINE = "offline",
    AWAY = "away",
    BUSY = "busy"
}

export enum MomentsType {
    IMAGE = "image",
    VIDEO = "video"
}

export enum CallsType {
    AUDIO = "audio",
    VIDEO = "video"
}

export enum JoinRequestsStatus {
    PENDING = "pending",
    ACCEPTED = "accepted",
    REJECTED = "rejected"
}

export enum UnorganicEmailsStatus {
    QUEUED = "queued",
    SENDING = "sending",
    SENT = "sent",
    SUPPRESSED = "suppressed",
    FAILED = "failed"
}

export enum FormsStatus {
    DRAFT = "draft",
    PUBLISHED = "published",
    CLOSED = "closed"
}

export enum FormsVisibility {
    PRIVATE = "private",
    PUBLIC = "public",
    WORKSPACE = "workspace"
}

export enum FormSubmissionsStatus {
    UNREAD = "unread",
    READ = "read",
    ARCHIVED = "archived",
    FLAGGED = "flagged"
}

export type Notes = Models.Row & {
    id: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    userId: string | null;
    isPublic: boolean | null;
    status: NotesStatus | null;
    parentNoteId: string | null;
    title: string | null;
    content: string | null;
    tags: string[] | null;
    comments: string[] | null;
    extensions: string[] | null;
    collaborators: string[] | null;
    metadata: string | null;
    attachments: string | null;
    format: string | null;
}

export type Tags = Models.Row & {
    id: string | null;
    name: string | null;
    notes: string[] | null;
    createdAt: string | null;
    color: string | null;
    description: string | null;
    usageCount: number | null;
    userId: string | null;
    nameLower: string | null;
}

export type Comments = Models.Row & {
    noteId: string;
    userId: string;
    content: string;
    createdAt: string;
    parentCommentId: string | null;
}

export type Extensions = Models.Row & {
    name: string;
    description: string | null;
    version: string | null;
    authorId: string | null;
    enabled: boolean | null;
    settings: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    isPublic: boolean | null;
}

export type Reactions = Models.Row & {
    targetType: ReactionsTargetType;
    emoji: string;
    createdAt: string;
    targetId: string;
    userId: string;
}

export type Collaborators = Models.Row & {
    noteId: string;
    userId: string;
    permission: CollaboratorsPermission;
    invitedAt: string | null;
    accepted: boolean | null;
}

export type ActivityLog = Models.Row & {
    userId: string;
    action: string;
    targetType: string;
    targetId: string;
    timestamp: string;
    details: string | null;
}

export type Settings = Models.Row & {
    userId: string;
    settings: string;
    createdAt: string | null;
    updatedAt: string | null;
    mode: string | null;
}

export type WalletMap = Models.Row & {
    walletAddressLower: string;
    userId: string;
    updatedAt: string | null;
}

export type NoteTags = Models.Row & {
    noteId: string;
    tagId: string;
    userId: string;
    createdAt: string | null;
    tag: string | null;
}

export type NoteRevisions = Models.Row & {
    noteId: string;
    revision: number;
    userId: string | null;
    title: string | null;
    content: string | null;
    createdAt: string | null;
    diff: string | null;
    diffFormat: string | null;
    fullSnapshot: boolean | null;
    cause: NoteRevisionsCause | null;
}

export type Subscriptions = Models.Row & {
    userId: string;
    plan: SubscriptionsPlan;
    status: SubscriptionsStatus | null;
    currentPeriodStart: string | null;
    currentPeriodEnd: string | null;
    seats: number | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type SecurityLogs = Models.Row & {
    userId: string;
    eventType: string;
    ipAddress: string | null;
    userAgent: string | null;
    deviceFingerprint: string | null;
    details: string | null;
    success: boolean;
    severity: string;
    timestamp: string;
}

export type Credentials = Models.Row & {
    userId: string;
    itemType: string;
    name: string;
    url: string | null;
    notes: string | null;
    totpId: string | null;
    password: string | null;
    cardNumber: string | null;
    cardholderName: string | null;
    cardExpiry: string | null;
    cardCVV: string | null;
    cardPIN: string | null;
    cardType: string | null;
    folderId: string | null;
    tags: string[] | null;
    customFields: string | null;
    faviconUrl: string | null;
    isFavorite: boolean;
    isDeleted: boolean;
    deletedAt: string | null;
    lastAccessedAt: string | null;
    passwordChangedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    username: string | null;
    sharedFrom: string | null;
}

export type Identities = Models.Row & {
    userId: string;
    identityType: string;
    label: string;
    credentialId: string | null;
    publicKey: string | null;
    counter: number;
    passkeyBlob: string | null;
    transports: string[] | null;
    aaguid: string | null;
    deviceInfo: string | null;
    isPrimary: boolean;
    isBackup: boolean;
    lastUsedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type User = Models.Row & {
    userId: string;
    email: string | null;
    masterpass: boolean | null;
    twofa: boolean | null;
    twofaSecret: string | null;
    backupCodes: string | null;
    isPasskey: boolean | null;
    sessionFingerprint: string | null;
    lastLoginAt: string | null;
    lastPasswordChangeAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type Folders = Models.Row & {
    userId: string;
    name: string;
    parentFolderId: string | null;
    icon: string | null;
    color: string | null;
    sortOrder: number;
    isDeleted: boolean;
    deletedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type TotpSecrets = Models.Row & {
    userId: string;
    issuer: string;
    accountName: string;
    secretKey: string;
    algorithm: string;
    digits: number;
    period: number;
    url: string | null;
    folderId: string | null;
    tags: string[] | null;
    isFavorite: boolean;
    isDeleted: boolean;
    deletedAt: string | null;
    lastUsedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    sharedFrom: string | null;
}

export type Keychain = Models.Row & {
    userId: string;
    type: string;
    credentialId: string | null;
    wrappedKey: string;
    salt: string;
    params: string | null;
    isBackup: boolean;
    createdAt: string | null;
    updatedAt: string | null;
}

export type KeyMapping = Models.Row & {
    resourceId: string;
    resourceType: string;
    grantee: string;
    wrappedKey: string;
    metadata: string | null;
}

export type Wallets = Models.Row & {
    ownerId: string;
    address: string;
    chain: string;
    encryptedSecret: string;
    type: string;
}

export type Messages = Models.Row & {
    conversationId: string;
    senderId: string;
    createdAt: string;
    updatedAt: string;
    type: MessagesType;
    content: string | null;
    attachments: string[] | null;
    replyTo: string | null;
    readBy: string[] | null;
}

export type Conversations = Models.Row & {
    type: ConversationsType;
    name: string | null;
    lastMessageId: string | null;
    lastMessageAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    creatorId: string;
    participants: string[] | null;
    admins: string[] | null;
    description: string | null;
    avatarUrl: string | null;
    avatarFileId: string | null;
    avatar: string | null;
    participantCount: number;
    maxParticipants: number;
    isEncrypted: boolean;
    encryptionVersion: string | null;
    encryptionKey: string | null;
    isPinned: string[];
    isMuted: string[];
    isArchived: string[];
    lastMessageText: string | null;
    lastMessageSenderId: string | null;
    unreadCount: string | null;
    settings: string | null;
    isPublic: boolean;
    inviteLink: string | null;
    inviteLinkExpiry: string | null;
    category: string | null;
    tags: string[];
    contextType: string | null;
    contextId: string | null;
    inviteMeta: string | null;
}

export type Contacts = Models.Row & {
    userId: string;
    contactUserId: string;
    nickname: string | null;
    relationship: ContactsRelationship;
    isBlocked: boolean;
    isFavorite: boolean;
    notes: string | null;
    tags: string[];
    lastInteraction: string | null;
    addedAt: string | null;
    updatedAt: string | null;
}

export type Follows = Models.Row & {
    followerId: string;
    followingId: string;
    status: FollowsStatus;
    isCloseFriend: boolean;
    notificationsEnabled: boolean;
    createdAt: string | null;
}

export type AppActivity = Models.Row & {
    userId: string;
    status: AppActivityStatus;
    lastSeen: string | null;
    customStatus: string | null;
}

export type Interactions = Models.Row & {
    messageId: string;
    userId: string;
    emoji: string;
    createdAt: string;
}

export type Moments = Models.Row & {
    userId: string;
    fileId: string;
    type: MomentsType;
    caption: string | null;
    createdAt: string;
    expiresAt: string;
    momentKind: string | null;
    sourceId: string | null;
    searchTitle: string | null;
}

export type Calls = Models.Row & {
    userId: string;
    type: CallsType;
    title: string | null;
    startsAt: string | null;
    expiresAt: string | null;
    metadata: string | null;
    receiverId: string | null;
    conversationId: string | null;
}

export type Epochs = Models.Row & {
    resourceId: string;
    epochNumber: number;
    createdBy: string;
}

export type ConversationMembers = Models.Row & {
    conversationId: string;
    userId: string;
}

export type Profiles = Models.Row & {
    username: string;
    displayName: string | null;
    bio: string | null;
    avatar: string | null;
    walletAddress: string | null;
    publicKey: string | null;
    status: string;
    preferences: string | null;
    userId: string;
}

export type MessageReactions = Models.Row & {
    conversationId: string;
    messageId: string;
    userId: string;
    emoji: string;
    createdAt: string;
}

export type JoinRequests = Models.Row & {
    resourceType: string;
    resourceId: string;
    requesterId: string;
    status: JoinRequestsStatus | null;
    createdAt: string | null;
    resolvedAt: string | null;
    resolvedBy: string | null;
}

export type UnorganicEmails = Models.Row & {
    eventType: string;
    sourceApp: string;
    actorId: string | null;
    recipientId: string | null;
    recipientEmail: string | null;
    resourceType: string | null;
    resourceId: string | null;
    templateKey: string;
    priority: number;
    status: UnorganicEmailsStatus;
    dedupeKey: string;
    attempts: number;
    sentAt: string | null;
    expiresAt: string | null;
    processedAt: string | null;
    blockedReason: string | null;
    metadata: string | null;
}

export type FocusSessions = Models.Row & {
    userId: string;
    taskId: string | null;
    startTime: string;
    endTime: string | null;
    duration: number;
    status: string;
}

export type EventGuests = Models.Row & {
    eventId: string;
    userId: string | null;
    email: string | null;
    status: string;
    role: string;
}

export type Events = Models.Row & {
    title: string;
    description: string | null;
    startTime: string;
    endTime: string;
    location: string | null;
    meetingUrl: string | null;
    visibility: string;
    status: string;
    coverImageId: string | null;
    maxAttendees: number;
    recurrenceRule: string | null;
    calendarId: string;
    userId: string;
}

export type Calendars = Models.Row & {
    name: string;
    color: string;
    isDefault: boolean;
    userId: string;
}

export type Tasks = Models.Row & {
    title: string;
    description: string | null;
    status: string;
    priority: string;
    dueDate: string | null;
    recurrenceRule: string | null;
    tags: string[] | null;
    assigneeIds: string[] | null;
    attachmentIds: string[] | null;
    eventId: string | null;
    userId: string;
    parentId: string | null;
}

export type Forms = Models.Row & {
    userId: string;
    title: string;
    description: string | null;
    schema: string;
    settings: string | null;
    status: FormsStatus;
    visibility: FormsVisibility;
}

export type FormSubmissions = Models.Row & {
    formId: string;
    submitterId: string | null;
    payload: string;
    status: FormSubmissionsStatus;
    metadata: string | null;
}

export type Agents = Models.Row & {
    ownerId: string;
    parentId: string | null;
    publicKey: string;
    config: string;
    status: string;
}
